### PR TITLE
Android app

### PR DESCRIPTION
**Pull request by madhavc**
Main functionality of the Application is completed. Few things left to do is add toolbar and logout button. 
Please do a code review and give some feedback. Meanwhile, I will continue to work on this.

### CODE REVIEW

**Comment by madhavc** [comment]
@gfosco any updates on the PR?

**Comment by gfosco** [comment]
Looks good to me, @madhavc.  I like that it's pretty much a direct port.

**Comment by madhavc** [comment]
@gfosco The Android App is finished, I have also updated the Readme #11. Please merge both #10  and #11. Thank you.

**Comment by gfosco** [comment]
Thanks @madhavc nice work! :+1:

**Pull request merged**
